version: '3.8'

services:
  web:
    build: ./marketplace
    restart: always
    command: gunicorn marketplace.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 80:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  celery-worker:
    build: ./marketplace
    restart: always
    command: celery --app=marketplace worker -l info
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:6.0.8-alpine
    restart: always

volumes:
  postgres_volume:
