version: '3.8'

services:
  web:
    build: ./marketplace
    restart: always
    command: gunicorn marketplace.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 80:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db

volumes:
  postgres_volume:
