# Generated by Django 2.2.19 on 2022-06-13 09:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemArchiveVersions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_version', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
                ('parent', models.CharField(max_length=36)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('price', models.IntegerField(blank=True, default=None, null=True, verbose_name='Цена')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
