# Generated by Django 2.2.19 on 2022-06-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220607_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemOldVersions',
            new_name='ItemArchiveVersions',
        ),
    ]
